[workspace]
members = ["attiny", "esp"]
resolver = "2"

[workspace.dependencies]
avr-device = "0.5.2"
embedded-hal = "0.2.7"
panic-halt = "0.2.0"
attiny-hal = { git = "https://github.com/rahix/avr-hal", features = [
    "rt",
    "attiny85",
], rev = "7b3e82a15e97e657559ec82cf934ba36c38312ec" }
avr-hal-generic = { git = "https://github.com/Rahix/avr-hal", rev = "7b3e82a15e97e657559ec82cf934ba36c38312ec" }
ads1x1x = "0.2.2"
strum = { version = "0.25.0", default-features = false, features = ["derive"] }
nb = "1.1.0"

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"
debug-assertions = false

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
debug-assertions = false
